// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'package:robotlegs_di/src/reflection/annotations.dart' as prefix3;
import 'package:robotlegs_di/src/reflection/reflector.dart' as prefix0;
import 'stuffs/product.dart' as prefix2;
import 'stuffs/shop.dart' as prefix1;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_transformer_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" show isTransformed;

final _data = {
  const prefix0.Reflect(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"Shop",
            r".Shop",
            7,
            0,
            const prefix0.Reflect(),
            const <int>[0, 1, 3, 4, 5, 6, 7, 12],
            const <int>[13, 14, 15, 16, 17, 3, 4, 5, 6, 7, 8, 9, 10, 11],
            const <int>[],
            3,
            {},
            {},
            {r"": (b) => () => b ? new prefix1.Shop() : null},
            0,
            0,
            const <int>[],
            const <Object>[const prefix0.Reflect()],
            null),
        new r.NonGenericClassMirrorImpl(
            r"ValueHolder",
            r".ValueHolder",
            7,
            1,
            const prefix0.Reflect(),
            const <int>[2, 19],
            const <int>[13, 14, 15, 16, 17, 18],
            const <int>[],
            3,
            {},
            {},
            {r"": (b) => (value) => b ? new prefix1.ValueHolder(value) : null},
            0,
            1,
            const <int>[],
            const <Object>[const prefix0.Reflect()],
            null),
        new r.NonGenericClassMirrorImpl(
            r"Product",
            r".Product",
            7,
            2,
            const prefix0.Reflect(),
            const <int>[20, 21, 22, 23, 24, 25, 26],
            const <int>[13, 14, 15, 16, 17, 20, 21, 22, 23, 24, 25],
            const <int>[],
            3,
            {},
            {},
            {r"": (b) => () => b ? new prefix2.Product() : null},
            1,
            2,
            const <int>[],
            const <Object>[const prefix0.Reflect()],
            null),
        new r.NonGenericClassMirrorImpl(
            r"Object",
            r"dart.core.Object",
            7,
            3,
            const prefix0.Reflect(),
            const <int>[13, 14, 15, 16, 17, 27],
            const <int>[13, 14, 15, 16, 17],
            const <int>[],
            null,
            {},
            {},
            {r"": (b) => () => b ? new Object() : null},
            2,
            3,
            const <int>[],
            const <Object>[],
            null)
      ],
      <m.DeclarationMirror>[
        new r.VariableMirrorImpl(r"product", 32773, 0, const prefix0.Reflect(),
            2, -1, -1, const <Object>[prefix3.inject]),
        new r.VariableMirrorImpl(r"otherProduct", 32773, 0,
            const prefix0.Reflect(), 2, -1, -1, const <Object>[prefix3.inject]),
        new r.VariableMirrorImpl(r"value", 33797, 1, const prefix0.Reflect(),
            -1, -1, -1, const <Object>[]),
        new r.MethodMirrorImpl(
            r"onPostConstruct",
            262146,
            0,
            null,
            -1,
            -1,
            const <int>[],
            const prefix0.Reflect(),
            const <Object>[prefix3.postConstruct]),
        new r.MethodMirrorImpl(
            r"onPreDestroy",
            262146,
            0,
            null,
            -1,
            -1,
            const <int>[],
            const prefix0.Reflect(),
            const <Object>[prefix3.preDestroy]),
        new r.MethodMirrorImpl(
            r"injectedMethod",
            262146,
            0,
            null,
            -1,
            -1,
            const <int>[],
            const prefix0.Reflect(),
            const <Object>[prefix3.inject]),
        new r.MethodMirrorImpl(
            r"withParamesInjectedMethod",
            262146,
            0,
            null,
            -1,
            -1,
            const <int>[0],
            const prefix0.Reflect(),
            const <Object>[prefix3.inject]),
        new r.MethodMirrorImpl(r"getValue", 131074, 0, -1, -1, -1,
            const <int>[], const prefix0.Reflect(), const <Object>[]),
        new r.ImplicitGetterMirrorImpl(const prefix0.Reflect(), 0, -1, -1, 8),
        new r.ImplicitSetterMirrorImpl(const prefix0.Reflect(), 0, -1, -1, 9),
        new r.ImplicitGetterMirrorImpl(const prefix0.Reflect(), 1, -1, -1, 10),
        new r.ImplicitSetterMirrorImpl(const prefix0.Reflect(), 1, -1, -1, 11),
        new r.MethodMirrorImpl(r"", 0, 0, -1, -1, -1, const <int>[],
            const prefix0.Reflect(), const <Object>[]),
        new r.MethodMirrorImpl(r"==", 131074, 3, -1, -1, -1, const <int>[3],
            const prefix0.Reflect(), const <Object>[]),
        new r.MethodMirrorImpl(r"toString", 131074, 3, -1, -1, -1,
            const <int>[], const prefix0.Reflect(), const <Object>[]),
        new r.MethodMirrorImpl(r"noSuchMethod", 65538, 3, null, -1, -1,
            const <int>[4], const prefix0.Reflect(), const <Object>[]),
        new r.MethodMirrorImpl(r"hashCode", 131075, 3, -1, -1, -1,
            const <int>[], const prefix0.Reflect(), const <Object>[]),
        new r.MethodMirrorImpl(r"runtimeType", 131075, 3, -1, -1, -1,
            const <int>[], const prefix0.Reflect(), const <Object>[]),
        new r.ImplicitGetterMirrorImpl(const prefix0.Reflect(), 2, -1, -1, 18),
        new r.MethodMirrorImpl(r"", 128, 1, -1, -1, -1, const <int>[5],
            const prefix0.Reflect(), const <Object>[]),
        new r.MethodMirrorImpl(
            r"postConstructMethod",
            262146,
            2,
            null,
            -1,
            -1,
            const <int>[],
            const prefix0.Reflect(),
            const <Object>[prefix3.postConstruct]),
        new r.MethodMirrorImpl(
            r"firstPostConstructMethod",
            262146,
            2,
            null,
            -1,
            -1,
            const <int>[],
            const prefix0.Reflect(),
            const <Object>[const prefix3.PostConstruct(order: 1)]),
        new r.MethodMirrorImpl(
            r"secondPostConstructMethod",
            262146,
            2,
            null,
            -1,
            -1,
            const <int>[],
            const prefix0.Reflect(),
            const <Object>[const prefix3.PostConstruct(order: 2)]),
        new r.MethodMirrorImpl(
            r"preDestroyMethod",
            262146,
            2,
            null,
            -1,
            -1,
            const <int>[],
            const prefix0.Reflect(),
            const <Object>[prefix3.preDestroy]),
        new r.MethodMirrorImpl(
            r"firstPreDestroyMethod",
            262146,
            2,
            null,
            -1,
            -1,
            const <int>[],
            const prefix0.Reflect(),
            const <Object>[const prefix3.PreDestroy(order: 1)]),
        new r.MethodMirrorImpl(
            r"secondPreDestroyMethod",
            262146,
            2,
            null,
            -1,
            -1,
            const <int>[],
            const prefix0.Reflect(),
            const <Object>[const prefix3.PreDestroy(order: 2)]),
        new r.MethodMirrorImpl(r"", 0, 2, -1, -1, -1, const <int>[],
            const prefix0.Reflect(), const <Object>[]),
        new r.MethodMirrorImpl(r"", 128, 3, -1, -1, -1, const <int>[],
            const prefix0.Reflect(), const <Object>[])
      ],
      <m.ParameterMirror>[
        new r.ParameterMirrorImpl(r"valueHolder", 32774, 6,
            const prefix0.Reflect(), 1, -1, -1, const <Object>[], null, null),
        new r.ParameterMirrorImpl(r"_product", 32870, 9,
            const prefix0.Reflect(), 2, -1, -1, const [], null, null),
        new r.ParameterMirrorImpl(r"_otherProduct", 32870, 11,
            const prefix0.Reflect(), 2, -1, -1, const [], null, null),
        new r.ParameterMirrorImpl(r"other", 16390, 13, const prefix0.Reflect(),
            null, -1, -1, const <Object>[], null, null),
        new r.ParameterMirrorImpl(r"invocation", 32774, 15,
            const prefix0.Reflect(), -1, -1, -1, const <Object>[], null, null),
        new r.ParameterMirrorImpl(r"value", 32774, 19, const prefix0.Reflect(),
            -1, -1, -1, const <Object>[], null, null)
      ],
      <Type>[prefix1.Shop, prefix1.ValueHolder, prefix2.Product, Object],
      4,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"onPostConstruct": (dynamic instance) => instance.onPostConstruct,
        r"onPreDestroy": (dynamic instance) => instance.onPreDestroy,
        r"injectedMethod": (dynamic instance) => instance.injectedMethod,
        r"withParamesInjectedMethod": (dynamic instance) =>
            instance.withParamesInjectedMethod,
        r"getValue": (dynamic instance) => instance.getValue,
        r"product": (dynamic instance) => instance.product,
        r"otherProduct": (dynamic instance) => instance.otherProduct,
        r"value": (dynamic instance) => instance.value,
        r"postConstructMethod": (dynamic instance) =>
            instance.postConstructMethod,
        r"firstPostConstructMethod": (dynamic instance) =>
            instance.firstPostConstructMethod,
        r"secondPostConstructMethod": (dynamic instance) =>
            instance.secondPostConstructMethod,
        r"preDestroyMethod": (dynamic instance) => instance.preDestroyMethod,
        r"firstPreDestroyMethod": (dynamic instance) =>
            instance.firstPreDestroyMethod,
        r"secondPreDestroyMethod": (dynamic instance) =>
            instance.secondPreDestroyMethod
      },
      {
        r"product=": (dynamic instance, value) => instance.product = value,
        r"otherProduct=": (dynamic instance, value) =>
            instance.otherProduct = value
      },
      <m.LibraryMirror>[
        new r.LibraryMirrorImpl(r"", Uri.parse(r"reflectable://0/"),
            const prefix0.Reflect(), const <int>[], {}, {}, const [], null),
        new r.LibraryMirrorImpl(r"", Uri.parse(r"reflectable://1/"),
            const prefix0.Reflect(), const <int>[], {}, {}, const [], null),
        new r.LibraryMirrorImpl(
            r"dart.core",
            Uri.parse(r"reflectable://2/dart.core"),
            const prefix0.Reflect(),
            const <int>[],
            {},
            {},
            const <Object>[],
            null)
      ],
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  if (!isTransformed) {
    throw new UnsupportedError(
        "The transformed code is running with the untransformed "
        "reflectable package. Remember to set your package-root to "
        "'build/.../packages'.");
  }
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
