name: robotlegs_di
version: 0.1.3
author: Hans Van den Keybus / Matej Simunic
description: Dependency Injection framework for Robotlegs for Google Dart
dependencies:
  reflectable: 2.0.0-dev.1.0

dev_dependencies:
  benchmark_harness: any
  test: any
