name: robotlegs_di
version: 0.1.0
author: Hans Van den Keybus
description: Dependency Injection framework for Robotlegs for Google Dart
dependencies:
  reflectable:
    path: ../reflectable
dev_dependencies:
  benchmark_harness: any
  test: any
